[2024-07-25T17:54:18.862+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T17:54:18.872+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: list_db_tables.get_table_names manual__2024-07-25T17:54:16.848810+00:00 [queued]>
[2024-07-25T17:54:18.876+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: list_db_tables.get_table_names manual__2024-07-25T17:54:16.848810+00:00 [queued]>
[2024-07-25T17:54:18.877+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-25T17:54:18.884+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): get_table_names> on 2024-07-25 17:54:16.848810+00:00
[2024-07-25T17:54:18.887+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=55) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-25T17:54:18.889+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'list_db_tables', 'get_table_names', 'manual__2024-07-25T17:54:16.848810+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/print_sql_request_dag.py', '--cfg-path', '/tmp/tmp8_4p8351']
[2024-07-25T17:54:18.890+0000] {standard_task_runner.py:64} INFO - Started process 57 to run task
[2024-07-25T17:54:18.890+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask get_table_names
[2024-07-25T17:54:18.916+0000] {task_command.py:426} INFO - Running <TaskInstance: list_db_tables.get_table_names manual__2024-07-25T17:54:16.848810+00:00 [running]> on host 9cfb47510abc
[2024-07-25T17:54:18.956+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='list_db_tables' AIRFLOW_CTX_TASK_ID='get_table_names' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T17:54:16.848810+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-25T17:54:16.848810+00:00'
[2024-07-25T17:54:18.958+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T17:54:18.958+0000] {sql.py:282} INFO - Executing: 
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public';
        
[2024-07-25T17:54:18.961+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T17:54:18.966+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 283, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 194, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 153, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `***_db` isn't defined
[2024-07-25T17:54:18.969+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=list_db_tables, task_id=get_table_names, run_id=manual__2024-07-25T17:54:16.848810+00:00, execution_date=20240725T175416, start_date=20240725T175418, end_date=20240725T175418
[2024-07-25T17:54:18.976+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task get_table_names (The conn_id `***_db` isn't defined; 57)
[2024-07-25T17:54:18.991+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T17:54:18.997+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-07-25T17:54:19.003+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T17:54:19.004+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
